export const LOGIN_FETCHING = "LOGIN_FETCHING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const LOGIN_STATUS = "LOGIN_STATUS"

export const TAGSCAN_FETCHING = "TAGSCAN_FETCHING";
export const TAGSCAN_SUCCESS = "TAGSCAN_SUCCESS";
export const TAGSCAN_FAILED = "TAGSCAN_FAILED";
export const TAGSCAN_CLEAR = "TAGSCAN_CLEAR";


export const LABELSCAN_COUNT = "LABELSCAN_COUNT";
export const LABELSCAN_CORRECT = "LABELSCAN_CORRECT";
export const LABELSCAN_INCORRECT = "LABELSCAN_INCORRECT";
export const LABELSCAN_CLEAR = "LABELSCAN_CLEAR";
export const LABELSCAN_FAILED = "LABELSCAN_FAILED";